# Generated by Django 5.1.6 on 2025-02-28 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='rubro',
        ),
    ]
