# Generated by Django 5.1.6 on 2025-02-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='estado',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('no_aprobado', 'No aprobado')], default='no_aprobado', max_length=15),
        ),
    ]
