# Generated by Django 5.1.6 on 2025-03-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_postulante_suscrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
