# Generated by Django 5.1.6 on 2025-02-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_postulante_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
