# Generated by Django 5.1.6 on 2025-02-28 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_remove_trabajo_rubro'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='rubro',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='pagina.rubro'),
            preserve_default=False,
        ),
    ]
