# Generated by Django 5.1.6 on 2025-03-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_trabajo_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='anonimo',
            field=models.BooleanField(default=False),
        ),
    ]
